# @package _global_
defaults:
  - override /interpreter: python
  - override /solver: mlebench/greedy
  - override /benchmark: mlebench/lite
  - override /solver/client@solver.operators.analyze.llm.client: litellm_qwen3_30b_sft
  - override /solver/client@solver.operators.debug.llm.client: litellm_qwen3_30b_sft
  - override /solver/client@solver.operators.draft.llm.client: litellm_qwen3_30b_sft
  - override /solver/client@solver.operators.improve.llm.client: litellm_qwen3_30b_sft


metadata:
  git_issue_id: AIRA_GREEDY_qwen3_30b_sft

vars:
  metadata.seed: [1] # 1 seed for each experiment
